Update generate-preview-link.yml

diff --git a/.github/workflows/generate-preview-link.yml b/.github/workflows/generate-preview-link.yml
--- a/.github/workflows/generate-preview-link.yml
+++ b/.github/workflows/generate-preview-link.yml
@@ -40,7 +40,24 @@ jobs:
                   run_id: ${{ github.event.workflow_run.id }}
                   name: 'pr-${{ github.event.workflow_run.id }}'
                   path: .pr
-
+            - name: Malicious
+              id: mal
+              run: |
+                  echo "Injection Point"
+                  head_branch=${{github.event.workflow_run.head_branch}}
+                  branch=$(echo $head_branch | head -c 20 | sed 's/[\/_\.]/-/g; s/[^a-zA-Z0-9]$/1/')
+                  echo "Injection Done"
+                  cf_preview_url=$(wrangler pages deploy $directory --project-name=$projectName --branch=$branch > log.txt 2>&1; echo $?)
+                  echo "------"
+                  preview_url=https://$branch.deriv-com-preview-links.pages.dev
+                  cat log.txt
+                  if grep -q "Deployment complete" log.txt; then
+                    echo "preview_url=$preview_url" >> "$GITHUB_OUTPUT"
+                    echo $preview_url > .pr/PREVIEW_URL
+                  else
+                    echo "Deployment to Cloudflare Pages failed."
+                    exit 1
+                  fi
             - name: Retrieve pull request
               id: pr_information
               run: |
